#version 450
#extension GL_EXT_debug_printf : enable
layout(push_constant) uniform PostProcess {
    vec4 params;
};

layout(binding = 0, set =  1) uniform sampler2D input_image;

layout(binding = 0, set=2, r32f) uniform writeonly image2D output_image;

#define POSTPROCESS_BLOCKSIZE 8

layout(local_size_x = POSTPROCESS_BLOCKSIZE, local_size_y = POSTPROCESS_BLOCKSIZE, local_size_z = 1) in;
void main() {
    ivec2 dispatch_id = ivec2(gl_GlobalInvocationID.xy);

    if (all(lessThan(dispatch_id.xy, ivec2(params.xy)))) {

		if(params.z == 0){
			vec4 texel0 = texelFetch(input_image, dispatch_id,0);
			imageStore(output_image,dispatch_id,texel0);
			return;
		}

        vec4 texel0 = texelFetch(input_image, dispatch_id * 2, 0);
		vec4 texel1 = texelFetch(input_image, dispatch_id * 2 + ivec2(1, 0), 0);
		vec4 texel2 = texelFetch(input_image, dispatch_id * 2 + ivec2(0, 1), 0);
		vec4 texel3 = texelFetch(input_image, dispatch_id * 2 + ivec2(1, 1), 0);

		vec4 depths = vec4(texel0.x, texel1.x, texel2.x, texel3.x);
		if(params.w == 0)
		{
			float min_depth = min(min(min(depths.x, depths.y), depths.z), depths.w);
		imageStore(output_image,dispatch_id,vec4(min_depth));}
		else {
			float max_depth = max(max(max(depths.x, depths.y), depths.z), depths.w);
			imageStore(output_image,dispatch_id,vec4(max_depth));
		}
    }
}
